version: "3.4"

services:
  zookeeper:
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - "mongo_data:/data/db"
    depends_on:
      - kafka
      
  mysql:
    image: mysql:latest
    ports:
      - "3307:3307"
    restart: always
    volumes:
      - "mysql_data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=techbankRootPsw
    depends_on:
      - mongo
      
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    depends_on:
      - mysql


volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongo_data:
    driver: local
  mysql_data:
    driver: local
   
networks:
  default:
    external:
      name: techbankNet
