
server:
  port: 5001

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    datasource:
      url: jdbc:mysql://localhost:3307/bankAccount?createDataBaseIfNotExits=true
      userName: root
      password: techbankRootPsw
    kafka:
      listener:
        ack-mode: MANUAL_IMMEDIATE
      consumer:
        bootstrap-server: localhost:9092
        group-id: bankaccCosumer
        auto-offser-reset: earliest
        key-deserialiser: org.apache.kafka.common.serialization.StringDeserializer
        value-deserialiser: org.springframework.kafa.support.serializer.JsonDeserializer
        properties:
          spring:
            json:
              trusted:
                packages: '*'
